$(document).ready(function(){
    $("#image-frame1").click(function(){
        $("#image-caption1").toggle("fast");
    });
    $("#image-frame2").click(function(){
        $("#image-caption2").toggle("slow");
    });
    $("#image-frame3").click(function(){
        $("#image-caption3").toggle("slow");
    });
});